In [1]:
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

#loading dataset
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

#Datacleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

c:\Users\rpran\anaconda3\envs\python_course\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [2]:
df.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,None,NaN,NaN,Boehringer Ingelheim,None,None
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,None,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,None,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,None,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,None,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."

In [3]:
df.tail()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
785736,Software Engineer,DevOps Engineer,Singapura,melalui Trabajo.org,Pekerjaan tetap,False,Singapore,2023-03-13 06:16:16,False,False,Singapore,None,NaN,NaN,CAREERSTAR INTERNATIONAL PTE. LTD.,"['bash', 'python', 'perl', 'linux', 'unix', 'k...","{'os': ['linux', 'unix'], 'other': ['kubernete..."
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,None,NaN,NaN,HABA FAMILYGROUP,"['sas', 'sas', 'sql', 'excel']","{'analyst_tools': ['sas', 'excel'], 'programmi..."
785738,Business Analyst,Commercial Analyst - Start Now,Malaysia,melalui Ricebowl,Pekerjaan tetap,False,Malaysia,2023-03-12 06:32:36,False,False,Malaysia,None,NaN,NaN,Lendlease Corporation,"['powerpoint', 'excel']","{'analyst_tools': ['powerpoint', 'excel']}"
785739,Data Engineer,"Principal Associate, Data Engineer (Remote-Eli...","Newark, New Jersey, Amerika Serikat",melalui Recruit.net,Pekerjaan tetap,False,Sudan,2023-03-12 06:32:15,False,False,Sudan,None,NaN,NaN,Capital One,"['python', 'go', 'nosql', 'sql', 'mongo', 'she...","{'cloud': ['aws', 'snowflake', 'azure', 'redsh..."
785740,Software Engineer,AWS System Analyst,India,melalui Trigyn,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,India,None,NaN,NaN,Trigyn,"['aws', 'flow']","{'cloud': ['aws'], 'other': ['flow']}"

In [4]:
# we can get a sample in a different way
df.sample()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
557394,Data Engineer,Machine Learning and Data Analysis Intern,"Zola Predosa, Metropolitan City of Bologna, Italy",via BeBee,Internship,False,Italy,2023-09-19 20:57:17,False,False,Italy,None,NaN,NaN,ManpowerGroup,None,None

In [5]:
df.sample(10)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
414345,Data Analyst,Data Analytics Training & Internship,Anywhere,via LinkedIn,Internship,True,Canada,2023-07-15 16:08:56,False,False,Canada,None,NaN,NaN,OESON,"['tableau', 'power bi']","{'analyst_tools': ['tableau', 'power bi']}"
771536,Data Analyst,"Data Analyst, Senior","Waltham, MA",via ZipRecruiter,Full-time,False,"New York, United States",2023-05-07 01:00:24,False,False,United States,None,NaN,NaN,McLean Hospital(MCL),"['sas', 'sas', 'python', 'sql']","{'analyst_tools': ['sas'], 'programming': ['sa..."
724332,Data Engineer,Principal Data Engineer,"Riverwoods, IL",via WANE Jobs,Full-time,False,"California, United States",2023-08-03 21:07:17,False,True,United States,None,NaN,NaN,Discover Financial Services,['unix'],{'os': ['unix']}
497791,Senior Data Scientist,Senior Data Scientist,"Munich, Germany",via BeBee Deutschland,Full-time,False,Germany,2023-02-01 11:59:37,False,False,Germany,None,NaN,NaN,Hoffmann Group,"['python', 'sql', 'scala', 'julia', 'c']","{'programming': ['python', 'sql', 'scala', 'ju..."
668871,Data Engineer,Data Engineer,"Birmingham, UK",via My Stateline Jobs,Full-time,False,United Kingdom,2023-06-28 11:00:55,True,False,United Kingdom,None,NaN,NaN,Harnham - Data & Analytics Recruitment,"['python', 'sql', 'aws', 'airflow']","{'cloud': ['aws'], 'libraries': ['airflow'], '..."
113744,Data Scientist,Looking for Online Data Science Instructor in...,"Bengaluru, Karnataka, India",via UrbanPro,Part-time,False,India,2023-10-08 00:10:50,False,False,India,None,NaN,NaN,UrbanPro.com,['zoom'],{'sync': ['zoom']}
470087,Data Scientist,Data Scientist F/H,"Boulogne-Billancourt, France",via Jobijoba,Full-time,False,France,2023-07-05 14:29:41,False,False,France,None,NaN,NaN,Le journal du Grand Paris,"['python', 'sql', 'gcp', 'aws', 'azure', 'git']","{'cloud': ['gcp', 'aws', 'azure'], 'other': ['..."
432525,Cloud Engineer,Solution Support Engineer - Customer Data Cloud,"Budapest, Hungary",via LinkedIn Hungary,Full-time,False,Hungary,2023-07-27 16:49:50,True,False,Hungary,None,NaN,NaN,SAP,"['html', 'css', 'javascript', 'sap']","{'analyst_tools': ['sap'], 'programming': ['ht..."
674968,Data Scientist,Data Science Assistant Intern,Anywhere,via LinkedIn,Full-time,True,"New York, United States",2023-02-26 10:02:48,False,False,United States,None,NaN,NaN,American Institutes for Research,"['python', 'r', 'sql', 'mysql', 'sql server']","{'databases': ['mysql', 'sql server'], 'progra..."
154159,Data Engineer,Big Data Engineer,"Lisbon, Portugal",via Empregos Trabajo.org,Full-time,False,Portugal,2023-03-24 08:26:21,False,False,Portugal,None,NaN,NaN,Dellent,"['databricks', 'azure', 'aws', 'pyspark', 'air...","{'analyst_tools': ['looker'], 'cloud': ['datab..."

In [7]:
# if you want the sample to never change 
df.sample(10, random_state=42)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
502901,Senior Data Engineer,Senior Data Engineer,"St Paul, MN",via BeBee,Full-time,False,"Florida, United States",2023-12-17 11:09:06,False,False,United States,None,NaN,NaN,ManpowerGroup,"['sql', 'azure', 'git']","{'cloud': ['azure'], 'other': ['git'], 'progra..."
406337,Senior Data Scientist,Senior Analytics Engineer,"London, UK",via LinkedIn,Full-time,False,United Kingdom,2023-10-06 16:09:56,False,False,United Kingdom,None,NaN,NaN,Harnham,"['sql', 'python', 'bigquery', 'snowflake', 'lo...","{'analyst_tools': ['looker'], 'cloud': ['bigqu..."
659951,Data Engineer,Data Engineer,"Newcastle upon Tyne, UK",via Indeed,Full-time,False,United Kingdom,2023-09-06 10:11:25,True,False,United Kingdom,None,NaN,NaN,Morgan King,None,None
541593,Data Analyst,Data Analyst,Malta,via Trabajo.org,Full-time,False,Malta,2023-02-14 21:14:18,True,False,Malta,None,NaN,NaN,Konnekt,['jira'],{'async': ['jira']}
425158,Senior Data Engineer,Senior Data Engineer. Job in Amsterdam NBC4i Jobs,"Amsterdam, Netherlands",via NBC4i Jobs,Full-time,False,Netherlands,2023-06-19 16:34:30,True,False,Netherlands,None,NaN,NaN,Independent Recruiters,['python'],{'programming': ['python']}
183426,Data Analyst,Data Analyst,Singapore,via Singapore | JobsDB,Full-time,False,Singapore,2023-11-09 16:07:57,False,False,Singapore,None,NaN,NaN,FLEXOSENSE PTE. LTD.,"['r', 'python', 'java', 'sql', 'sql server', '...","{'analyst_tools': ['tableau'], 'cloud': ['orac..."
287790,Data Analyst,Data Analyst,"Tampa, FL",via LinkedIn,Full-time,False,"Florida, United States",2023-07-14 17:02:23,True,False,United States,None,NaN,NaN,Iris Software Inc.,"['sql', 'hadoop', 'excel']","{'analyst_tools': ['excel'], 'libraries': ['ha..."
541983,Data Analyst,"Data Analyst, Cloud Systems Jobs","Chantilly, VA",via Clearance Jobs,Full-time,False,Georgia,2023-06-15 19:44:34,False,False,United States,None,NaN,NaN,SAIC,"['sql', 'r', 'matlab', 'python', 'oracle', 'aw...","{'analyst_tools': ['power bi', 'tableau', 'qli..."
416896,Data Scientist,Alternant Actuariat & Data Science H/F,France,via LinkedIn,Full-time,False,France,2023-09-22 16:47:24,False,False,France,None,NaN,NaN,KPMG France,None,None
780907,Data Engineer,"Data Engineer with Fivetran,Qlik Must","Mexico City, CDMX, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-16 06:19:09,False,False,Mexico,None,NaN,NaN,CORUS Consulting,"['oracle', 'snowflake', 'aws', 'azure', 'alter...","{'analyst_tools': ['alteryx'], 'cloud': ['orac..."

In [8]:
df.sample(10, random_state=42) # u will get the same sample until u use the seed number is the same ie 42

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
502901,Senior Data Engineer,Senior Data Engineer,"St Paul, MN",via BeBee,Full-time,False,"Florida, United States",2023-12-17 11:09:06,False,False,United States,None,NaN,NaN,ManpowerGroup,"['sql', 'azure', 'git']","{'cloud': ['azure'], 'other': ['git'], 'progra..."
406337,Senior Data Scientist,Senior Analytics Engineer,"London, UK",via LinkedIn,Full-time,False,United Kingdom,2023-10-06 16:09:56,False,False,United Kingdom,None,NaN,NaN,Harnham,"['sql', 'python', 'bigquery', 'snowflake', 'lo...","{'analyst_tools': ['looker'], 'cloud': ['bigqu..."
659951,Data Engineer,Data Engineer,"Newcastle upon Tyne, UK",via Indeed,Full-time,False,United Kingdom,2023-09-06 10:11:25,True,False,United Kingdom,None,NaN,NaN,Morgan King,None,None
541593,Data Analyst,Data Analyst,Malta,via Trabajo.org,Full-time,False,Malta,2023-02-14 21:14:18,True,False,Malta,None,NaN,NaN,Konnekt,['jira'],{'async': ['jira']}
425158,Senior Data Engineer,Senior Data Engineer. Job in Amsterdam NBC4i Jobs,"Amsterdam, Netherlands",via NBC4i Jobs,Full-time,False,Netherlands,2023-06-19 16:34:30,True,False,Netherlands,None,NaN,NaN,Independent Recruiters,['python'],{'programming': ['python']}
183426,Data Analyst,Data Analyst,Singapore,via Singapore | JobsDB,Full-time,False,Singapore,2023-11-09 16:07:57,False,False,Singapore,None,NaN,NaN,FLEXOSENSE PTE. LTD.,"['r', 'python', 'java', 'sql', 'sql server', '...","{'analyst_tools': ['tableau'], 'cloud': ['orac..."
287790,Data Analyst,Data Analyst,"Tampa, FL",via LinkedIn,Full-time,False,"Florida, United States",2023-07-14 17:02:23,True,False,United States,None,NaN,NaN,Iris Software Inc.,"['sql', 'hadoop', 'excel']","{'analyst_tools': ['excel'], 'libraries': ['ha..."
541983,Data Analyst,"Data Analyst, Cloud Systems Jobs","Chantilly, VA",via Clearance Jobs,Full-time,False,Georgia,2023-06-15 19:44:34,False,False,United States,None,NaN,NaN,SAIC,"['sql', 'r', 'matlab', 'python', 'oracle', 'aw...","{'analyst_tools': ['power bi', 'tableau', 'qli..."
416896,Data Scientist,Alternant Actuariat & Data Science H/F,France,via LinkedIn,Full-time,False,France,2023-09-22 16:47:24,False,False,France,None,NaN,NaN,KPMG France,None,None
780907,Data Engineer,"Data Engineer with Fivetran,Qlik Must","Mexico City, CDMX, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-16 06:19:09,False,False,Mexico,None,NaN,NaN,CORUS Consulting,"['oracle', 'snowflake', 'aws', 'azure', 'alter...","{'analyst_tools': ['alteryx'], 'cloud': ['orac..."

# Copy()

In [17]:
dataset = load_dataset('lukebarousse/data_jobs')
df_orginal = dataset['train'].to_pandas()

In [18]:
# Until now instead of using this method we were simply assigning dataframes
df_altered = df_orginal
# below we will see the problem of doing this way

In [19]:
# just like before we will fill the Nan values with median
median_salary = df_altered['salary_year_avg'].median()
median_salary

115000.0

In [21]:
df_altered['salary_year_avg'] = df_altered['salary_year_avg'].fillna(median_salary)
df_altered['salary_year_avg']

0         115000.0
1         115000.0
2         115000.0
3         115000.0
4         115000.0
            ...
785736    115000.0
785737    115000.0
785738    115000.0
785739    115000.0
785740    115000.0
Name: salary_year_avg, Length: 785741, dtype: float64

In [ ]:
# now when we call the orginal dataframe we think that it might still have Nan values but it doesnt it also changed
df_orginal['salary_year_avg']

0         115000.0
1         115000.0
2         115000.0
3         115000.0
4         115000.0
            ...
785736    115000.0
785737    115000.0
785738    115000.0
785739    115000.0
785740    115000.0
Name: salary_year_avg, Length: 785741, dtype: float64

In [ ]:
id(df_altered) == id(df_orginal) # see both of the dataframes have the same id

True

In [24]:
# so inorder to keep the orginal dataframe intact we must use copy()
dataset = load_dataset('lukebarousse/data_jobs')
df_orginal = dataset['train'].to_pandas()

df_altered = df_orginal.copy()

In [25]:
# now we do the same thing
median_salary = df_altered['salary_year_avg'].median()
median_salary

115000.0

In [26]:
df_altered['salary_year_avg'] = df_altered['salary_year_avg'].fillna(median_salary)
df_altered['salary_year_avg']

0         115000.0
1         115000.0
2         115000.0
3         115000.0
4         115000.0
            ...
785736    115000.0
785737    115000.0
785738    115000.0
785739    115000.0
785740    115000.0
Name: salary_year_avg, Length: 785741, dtype: float64

In [27]:
df_orginal['salary_year_avg']

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
          ..
785736   NaN
785737   NaN
785738   NaN
785739   NaN
785740   NaN
Name: salary_year_avg, Length: 785741, dtype: float64

In [28]:
print(f'id number of df_orginal     : {id(df_orginal)}')
print(f'id number of df_altered     : {id(df_altered)}')
print(f'Are both the dataframe same?: {id(df_orginal) == id(df_altered)}')

id number of df_orginal     : 2041245356432
id number of df_altered     : 2040819736336
Are both the dataframe same?: False